apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui-service
  type: LoadBalancer
  loadBalancerIP: 34.66.138.117
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels: 
        app: ui-service  
    spec:                      
      containers: 
      - name: ui-service 
        image: iamchaitanyakulkarni/uiservice:4
        ports:
        - containerPort: 5000
        resources: 
            limits: 
              cpu: 256m
            requests:
              cpu: 100m
        env:
          - name: STOCKS_URL
            value: http://34.66.138.117:4000
          - name: USERS_URL
            value: http://34.66.138.117:3000